[pytest]
# 默认命令行参数
addopts = -v --alluredir=.allure-results --clean-alluredir --headed
# --reruns 3 --reruns-delay 1
testpaths= tests
markers =
    unit: 单测用例
    ui: 标记UI自动化用例
    api：标记接口自动化用例
    forboe: boe环境测试用例
    forppe: ppe环境测试用例